services:
    postgres:
        image: postgres:alpine
        container_name: nilacare-postgres-dev
        restart: unless-stopped
        environment:
            POSTGRES_DB: nilacare
            POSTGRES_USER: nilacare_user
            POSTGRES_PASSWORD: nilacare_user_password
        ports:
            - '5432:5432'
        volumes:
            - nilacare_postgres_data_dev:/var/lib/postgresql/data
        healthcheck:
            test: [ 'CMD-SHELL', 'pg_isready -U nilacare_user -d nilacare' ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

volumes:
    nilacare_postgres_data_dev:
