// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { RegisterV1Data, RegisterV1Responses, LoginV1Data, LoginV1Responses, GetAllProjectsV1Data, GetAllProjectsV1Responses, CreateProjectV1Data, CreateProjectV1Responses, DeleteProjectV1Data, DeleteProjectV1Responses, GetProjectByIdV1Data, GetProjectByIdV1Responses, UpdateProjectV1Data, UpdateProjectV1Responses, GetAllTasksV1Data, GetAllTasksV1Responses, CreateTaskV1Data, CreateTaskV1Responses, DeleteTaskV1Data, DeleteTaskV1Responses, GetTaskByIdV1Data, GetTaskByIdV1Responses, UpdateTaskV1Data, UpdateTaskV1Responses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const registerV1 = <ThrowOnError extends boolean = false>(options: Options<RegisterV1Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RegisterV1Responses, unknown, ThrowOnError>({
        url: '/v1/user/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const loginV1 = <ThrowOnError extends boolean = false>(options: Options<LoginV1Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LoginV1Responses, unknown, ThrowOnError>({
        url: '/v1/user/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllProjectsV1 = <ThrowOnError extends boolean = false>(options?: Options<GetAllProjectsV1Data, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllProjectsV1Responses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/projects',
        ...options
    });
};

export const createProjectV1 = <ThrowOnError extends boolean = false>(options: Options<CreateProjectV1Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateProjectV1Responses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/projects',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const deleteProjectV1 = <ThrowOnError extends boolean = false>(options: Options<DeleteProjectV1Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteProjectV1Responses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/projects/{id}',
        ...options
    });
};

export const getProjectByIdV1 = <ThrowOnError extends boolean = false>(options: Options<GetProjectByIdV1Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetProjectByIdV1Responses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/projects/{id}',
        ...options
    });
};

export const updateProjectV1 = <ThrowOnError extends boolean = false>(options: Options<UpdateProjectV1Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UpdateProjectV1Responses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/projects/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAllTasksV1 = <ThrowOnError extends boolean = false>(options?: Options<GetAllTasksV1Data, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllTasksV1Responses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/tasks',
        ...options
    });
};

export const createTaskV1 = <ThrowOnError extends boolean = false>(options: Options<CreateTaskV1Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateTaskV1Responses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/tasks',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const deleteTaskV1 = <ThrowOnError extends boolean = false>(options: Options<DeleteTaskV1Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteTaskV1Responses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/tasks/{id}',
        ...options
    });
};

export const getTaskByIdV1 = <ThrowOnError extends boolean = false>(options: Options<GetTaskByIdV1Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetTaskByIdV1Responses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/tasks/{id}',
        ...options
    });
};

export const updateTaskV1 = <ThrowOnError extends boolean = false>(options: Options<UpdateTaskV1Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UpdateTaskV1Responses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/tasks/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};