// This file is auto-generated by @hey-api/openapi-ts

export type RegisterBody = {
    email: string;
    /**
     * Password must be at least 6 characters long
     */
    password: string;
};

export type RegisterResponse = {
    user: {
        id: number;
        email: string;
    };
    /**
     * JWT token for authentication
     */
    token: string;
};

export type LoginBody = {
    email: string;
    /**
     * Password must be at least 6 characters long
     */
    password: string;
};

export type LoginResponse = {
    user: {
        id: number;
        email: string;
    };
    /**
     * JWT token for authentication
     */
    token: string;
};

export type CreateProjectBody = {
    name: string;
    description?: string;
};

export type CreateProjectResponse = {
    id: number;
    name: string;
    description: string | null;
};

export type GetAllProjectsResponse = Array<{
    id: number;
    name: string;
    description: string | null;
}>;

export type GetProjectByIdResponse = {
    id: number;
    name: string;
    description: string | null;
};

export type UpdateProjectBody = {
    name?: string;
    description?: string;
};

export type UpdateProjectResponse = {
    id: number;
    name: string;
    description: string | null;
};

export type DeleteProjectResponse = {
    id: number;
    name: string;
    description: string | null;
};

export type CreateTaskBody = {
    title: string;
    description?: string;
    status?: 'todo' | 'in_progress' | 'done';
    priority?: 'low' | 'medium' | 'high';
    projectId: number;
};

export type CreateTaskResponse = {
    id: number;
    title: string;
    description: string | null;
    status: 'todo' | 'in_progress' | 'done';
    priority: 'low' | 'medium' | 'high';
    projectId: number;
};

export type GetAllTasksResponse = Array<{
    id: number;
    title: string;
    description: string | null;
    status: 'todo' | 'in_progress' | 'done';
    priority: 'low' | 'medium' | 'high';
    projectId: number;
}>;

export type GetTaskByIdResponse = {
    id: number;
    title: string;
    description: string | null;
    status: 'todo' | 'in_progress' | 'done';
    priority: 'low' | 'medium' | 'high';
    projectId: number;
};

export type UpdateTaskBody = {
    title?: string;
    description?: string;
    status?: 'todo' | 'in_progress' | 'done';
    priority?: 'low' | 'medium' | 'high';
};

export type UpdateTaskResponse = {
    id: number;
    title: string;
    description: string | null;
    status: 'todo' | 'in_progress' | 'done';
    priority: 'low' | 'medium' | 'high';
    projectId: number;
};

export type DeleteTaskResponse = {
    id: number;
    title: string;
    description: string | null;
    status: 'todo' | 'in_progress' | 'done';
    priority: 'low' | 'medium' | 'high';
    projectId: number;
};

export type RegisterV1Data = {
    body: RegisterBody;
    path?: never;
    query?: never;
    url: '/v1/auth/register';
};

export type RegisterV1Responses = {
    200: RegisterResponse;
};

export type RegisterV1Response = RegisterV1Responses[keyof RegisterV1Responses];

export type LoginV1Data = {
    body: LoginBody;
    path?: never;
    query?: never;
    url: '/v1/auth/login';
};

export type LoginV1Responses = {
    200: LoginResponse;
};

export type LoginV1Response = LoginV1Responses[keyof LoginV1Responses];

export type GetAllProjectsV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/projects';
};

export type GetAllProjectsV1Responses = {
    200: GetAllProjectsResponse;
};

export type GetAllProjectsV1Response = GetAllProjectsV1Responses[keyof GetAllProjectsV1Responses];

export type CreateProjectV1Data = {
    body: CreateProjectBody;
    path?: never;
    query?: never;
    url: '/v1/projects';
};

export type CreateProjectV1Responses = {
    200: CreateProjectResponse;
};

export type CreateProjectV1Response = CreateProjectV1Responses[keyof CreateProjectV1Responses];

export type DeleteProjectV1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/v1/projects/{id}';
};

export type DeleteProjectV1Responses = {
    200: DeleteProjectResponse;
};

export type DeleteProjectV1Response = DeleteProjectV1Responses[keyof DeleteProjectV1Responses];

export type GetProjectByIdV1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/v1/projects/{id}';
};

export type GetProjectByIdV1Responses = {
    200: GetProjectByIdResponse;
};

export type GetProjectByIdV1Response = GetProjectByIdV1Responses[keyof GetProjectByIdV1Responses];

export type UpdateProjectV1Data = {
    body: UpdateProjectBody;
    path: {
        id: number;
    };
    query?: never;
    url: '/v1/projects/{id}';
};

export type UpdateProjectV1Responses = {
    200: UpdateProjectResponse;
};

export type UpdateProjectV1Response = UpdateProjectV1Responses[keyof UpdateProjectV1Responses];

export type GetAllTasksV1Data = {
    body?: never;
    path?: never;
    query?: {
        filter?: {
            status?: 'todo' | 'in_progress' | 'done';
            priority?: 'low' | 'medium' | 'high';
            projectId?: number;
        };
    };
    url: '/v1/tasks';
};

export type GetAllTasksV1Responses = {
    200: GetAllTasksResponse;
};

export type GetAllTasksV1Response = GetAllTasksV1Responses[keyof GetAllTasksV1Responses];

export type CreateTaskV1Data = {
    body: CreateTaskBody;
    path?: never;
    query?: never;
    url: '/v1/tasks';
};

export type CreateTaskV1Responses = {
    200: CreateTaskResponse;
};

export type CreateTaskV1Response = CreateTaskV1Responses[keyof CreateTaskV1Responses];

export type DeleteTaskV1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/v1/tasks/{id}';
};

export type DeleteTaskV1Responses = {
    200: DeleteTaskResponse;
};

export type DeleteTaskV1Response = DeleteTaskV1Responses[keyof DeleteTaskV1Responses];

export type GetTaskByIdV1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/v1/tasks/{id}';
};

export type GetTaskByIdV1Responses = {
    200: GetTaskByIdResponse;
};

export type GetTaskByIdV1Response = GetTaskByIdV1Responses[keyof GetTaskByIdV1Responses];

export type UpdateTaskV1Data = {
    body: UpdateTaskBody;
    path: {
        id: number;
    };
    query?: never;
    url: '/v1/tasks/{id}';
};

export type UpdateTaskV1Responses = {
    200: UpdateTaskResponse;
};

export type UpdateTaskV1Response = UpdateTaskV1Responses[keyof UpdateTaskV1Responses];

export type ClientOptions = {
    baseUrl: string;
};