// This file is auto-generated by @hey-api/openapi-ts

import { type Options, registerV1, loginV1, getAllProjectsV1, createProjectV1, deleteProjectV1, getProjectByIdV1, updateProjectV1, searchTasksV1, createTaskV1, deleteTaskV1, getTaskByIdV1, updateTaskV1 } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError } from '@tanstack/react-query';
import type { RegisterV1Data, RegisterV1Response, LoginV1Data, LoginV1Response, GetAllProjectsV1Data, CreateProjectV1Data, CreateProjectV1Response, DeleteProjectV1Data, DeleteProjectV1Response, GetProjectByIdV1Data, UpdateProjectV1Data, UpdateProjectV1Response, SearchTasksV1Data, CreateTaskV1Data, CreateTaskV1Response, DeleteTaskV1Data, DeleteTaskV1Response, GetTaskByIdV1Data, UpdateTaskV1Data, UpdateTaskV1Response } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const registerV1QueryKey = (options: Options<RegisterV1Data>) => createQueryKey('registerV1', options);

export const registerV1Options = (options: Options<RegisterV1Data>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await registerV1({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: registerV1QueryKey(options)
    });
};

export const registerV1Mutation = (options?: Partial<Options<RegisterV1Data>>): UseMutationOptions<RegisterV1Response, DefaultError, Options<RegisterV1Data>> => {
    const mutationOptions: UseMutationOptions<RegisterV1Response, DefaultError, Options<RegisterV1Data>> = {
        mutationFn: async (localOptions) => {
            const { data } = await registerV1({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const loginV1QueryKey = (options: Options<LoginV1Data>) => createQueryKey('loginV1', options);

export const loginV1Options = (options: Options<LoginV1Data>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await loginV1({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: loginV1QueryKey(options)
    });
};

export const loginV1Mutation = (options?: Partial<Options<LoginV1Data>>): UseMutationOptions<LoginV1Response, DefaultError, Options<LoginV1Data>> => {
    const mutationOptions: UseMutationOptions<LoginV1Response, DefaultError, Options<LoginV1Data>> = {
        mutationFn: async (localOptions) => {
            const { data } = await loginV1({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAllProjectsV1QueryKey = (options?: Options<GetAllProjectsV1Data>) => createQueryKey('getAllProjectsV1', options);

export const getAllProjectsV1Options = (options?: Options<GetAllProjectsV1Data>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAllProjectsV1({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAllProjectsV1QueryKey(options)
    });
};

export const createProjectV1QueryKey = (options: Options<CreateProjectV1Data>) => createQueryKey('createProjectV1', options);

export const createProjectV1Options = (options: Options<CreateProjectV1Data>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await createProjectV1({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createProjectV1QueryKey(options)
    });
};

export const createProjectV1Mutation = (options?: Partial<Options<CreateProjectV1Data>>): UseMutationOptions<CreateProjectV1Response, DefaultError, Options<CreateProjectV1Data>> => {
    const mutationOptions: UseMutationOptions<CreateProjectV1Response, DefaultError, Options<CreateProjectV1Data>> = {
        mutationFn: async (localOptions) => {
            const { data } = await createProjectV1({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteProjectV1Mutation = (options?: Partial<Options<DeleteProjectV1Data>>): UseMutationOptions<DeleteProjectV1Response, DefaultError, Options<DeleteProjectV1Data>> => {
    const mutationOptions: UseMutationOptions<DeleteProjectV1Response, DefaultError, Options<DeleteProjectV1Data>> = {
        mutationFn: async (localOptions) => {
            const { data } = await deleteProjectV1({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getProjectByIdV1QueryKey = (options: Options<GetProjectByIdV1Data>) => createQueryKey('getProjectByIdV1', options);

export const getProjectByIdV1Options = (options: Options<GetProjectByIdV1Data>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getProjectByIdV1({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getProjectByIdV1QueryKey(options)
    });
};

export const updateProjectV1Mutation = (options?: Partial<Options<UpdateProjectV1Data>>): UseMutationOptions<UpdateProjectV1Response, DefaultError, Options<UpdateProjectV1Data>> => {
    const mutationOptions: UseMutationOptions<UpdateProjectV1Response, DefaultError, Options<UpdateProjectV1Data>> = {
        mutationFn: async (localOptions) => {
            const { data } = await updateProjectV1({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const searchTasksV1QueryKey = (options?: Options<SearchTasksV1Data>) => createQueryKey('searchTasksV1', options);

export const searchTasksV1Options = (options?: Options<SearchTasksV1Data>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await searchTasksV1({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: searchTasksV1QueryKey(options)
    });
};

export const createTaskV1QueryKey = (options: Options<CreateTaskV1Data>) => createQueryKey('createTaskV1', options);

export const createTaskV1Options = (options: Options<CreateTaskV1Data>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await createTaskV1({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createTaskV1QueryKey(options)
    });
};

export const createTaskV1Mutation = (options?: Partial<Options<CreateTaskV1Data>>): UseMutationOptions<CreateTaskV1Response, DefaultError, Options<CreateTaskV1Data>> => {
    const mutationOptions: UseMutationOptions<CreateTaskV1Response, DefaultError, Options<CreateTaskV1Data>> = {
        mutationFn: async (localOptions) => {
            const { data } = await createTaskV1({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteTaskV1Mutation = (options?: Partial<Options<DeleteTaskV1Data>>): UseMutationOptions<DeleteTaskV1Response, DefaultError, Options<DeleteTaskV1Data>> => {
    const mutationOptions: UseMutationOptions<DeleteTaskV1Response, DefaultError, Options<DeleteTaskV1Data>> = {
        mutationFn: async (localOptions) => {
            const { data } = await deleteTaskV1({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTaskByIdV1QueryKey = (options: Options<GetTaskByIdV1Data>) => createQueryKey('getTaskByIdV1', options);

export const getTaskByIdV1Options = (options: Options<GetTaskByIdV1Data>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getTaskByIdV1({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getTaskByIdV1QueryKey(options)
    });
};

export const updateTaskV1Mutation = (options?: Partial<Options<UpdateTaskV1Data>>): UseMutationOptions<UpdateTaskV1Response, DefaultError, Options<UpdateTaskV1Data>> => {
    const mutationOptions: UseMutationOptions<UpdateTaskV1Response, DefaultError, Options<UpdateTaskV1Data>> = {
        mutationFn: async (localOptions) => {
            const { data } = await updateTaskV1({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};